#!/usr/bin/env python3
"""Export the PPO ONNX policy to the TypeScript weight module used at runtime.

The exported graph is a plain MLP (Gemm + Tanh), so the dashboard reimplements
the forward pass in TypeScript (`src/lib/ppo/policy.ts`) instead of bundling an
ONNX runtime into the Vercel deployment. This script is the only step that needs
Python; run it whenever the checkpoint changes.

    pip install onnx
    python scripts/export-ppo-weights.py

Optionally point at a different checkpoint:

    python scripts/export-ppo-weights.py --model path/to/policy.onnx
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import textwrap
from pathlib import Path

import numpy as np
import onnx
from onnx import numpy_helper

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MODEL = REPO_ROOT / "models" / "ppo_policy_100k.onnx"
DEFAULT_OUTPUT = REPO_ROOT / "src" / "lib" / "ppo" / "ppo-weights.ts"

# Order matters: policy.ts reads tensors by name, but the blob layout below is
# what the generated offsets refer to.
TENSOR_NAMES = [
    "mlp_extractor.policy_net.0.weight",
    "mlp_extractor.policy_net.0.bias",
    "mlp_extractor.policy_net.2.weight",
    "mlp_extractor.policy_net.2.bias",
    "action_net.weight",
    "action_net.bias",
    "mlp_extractor.value_net.0.weight",
    "mlp_extractor.value_net.0.bias",
    "mlp_extractor.value_net.2.weight",
    "mlp_extractor.value_net.2.bias",
    "value_net.weight",
    "value_net.bias",
    "log_std",
]


def build_blob(model_path: Path):
    model = onnx.load(model_path.as_posix())
    initializers = {i.name: numpy_helper.to_array(i) for i in model.graph.initializer}

    missing = [name for name in TENSOR_NAMES if name not in initializers]
    if missing:
        raise SystemExit(f"Checkpoint is missing expected tensors: {missing}")

    entries = []
    blob = bytearray()
    for name in TENSOR_NAMES:
        array = np.ascontiguousarray(initializers[name], dtype=np.float32)
        entries.append(
            {
                "name": name,
                "dims": list(array.shape),
                "offset": len(blob) // 4,
                "count": int(array.size),
            }
        )
        blob += array.tobytes()  # little-endian float32

    return entries, bytes(blob)


def render_module(entries, blob: bytes, sha256: str) -> str:
    b64 = base64.b64encode(blob).decode("ascii")
    chunks = textwrap.wrap(b64, 96)
    literal = "\n".join(f'  "{c}" +' for c in chunks[:-1]) + f'\n  "{chunks[-1]}";'

    layout = ",\n".join(
        '  "{name}": {{ dims: [{dims}], offset: {offset}, count: {count} }}'.format(
            name=e["name"],
            dims=", ".join(str(d) for d in e["dims"]),
            offset=e["offset"],
            count=e["count"],
        )
        for e in entries
    )
    total = entries[-1]["offset"] + entries[-1]["count"]

    return f'''/**
 * PPO policy weights extracted from `ppo_trader_onnx/ppo_policy_100k.onnx`
 * (deep-rl-trading-agent, Stable-Baselines3 PPO, 100k steps).
 *
 * Generated by `npm run model:export` — do not edit by hand.
 *
 * The graph is a plain MLP (Gemm + Tanh only), so it is re-implemented in
 * TypeScript in `policy.ts` instead of shipping an ONNX runtime. All tensors
 * are float32, concatenated in the order below and base64-encoded.
 *
 * Source model SHA-256: {sha256}
 */

export const PPO_MODEL_SHA256 =
  "{sha256}";

export interface TensorSpec {{
  dims: number[];
  /** Offset into the decoded Float32Array, in floats (not bytes). */
  offset: number;
  count: number;
}}

export const PPO_TENSOR_LAYOUT = {{
{layout},
}} as const satisfies Record<string, TensorSpec>;

export type PpoTensorName = keyof typeof PPO_TENSOR_LAYOUT;

export const PPO_WEIGHTS_FLOAT_COUNT = {total};

/** Base64-encoded little-endian float32 blob of every tensor above. */
export const PPO_WEIGHTS_BASE64 =
{literal}
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    if not args.model.exists():
        raise SystemExit(f"Checkpoint not found: {args.model}")

    sha256 = hashlib.sha256(args.model.read_bytes()).hexdigest()
    entries, blob = build_blob(args.model)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_module(entries, blob, sha256))

    print(f"{args.model.name} -> {args.out.relative_to(REPO_ROOT)}")
    print(f"  tensors: {len(entries)}  floats: {len(blob) // 4}  sha256: {sha256[:16]}…")


if __name__ == "__main__":
    main()
